import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jose' at '5/17/16 11:37 PM' with Gradle 2.13
 *
 * @author jose, @date 5/17/16 11:37 PM
 */
public class LibraryTest {
	
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
