/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jose' at '5/17/16 11:37 PM' with Gradle 2.13
 *
 * @author jose, @date 5/17/16 11:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
